.TH mpkg-which 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-which
.SH СИНТАКСИС
.B mpkg-which
[
.B -v --verbose
]
[
.B -g --dialog
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ФАЙЛА
.SH ОПИСАНИЕ
Поиск пакетов, содержащих указанный файл. В отличие от 
.B mpkg-filesearch,
ищет точное соответствие. В остальном эти две команды идентичны. 
.SH КЛЮЧИ
.TP
.B -v --verbose
подробно показывать какие именно файлы были найдены, иначе будут отображаться только найденные пакеты.
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
