.TH mpkg-menu 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-menu
.SH СИНТАКСИС
.B mpkg-menu [КЛЮЧИ]
.SH ОПИСАНИЕ
Псевдографический интерфейс к mpkg.
.SH ДОПУСТИМЫЕ КЛЮЧИ
Впринципе, допустимы все ключи из любых команд. Они будут иметь действие на ту область, которая будет выполняться из меню. По каждому действию - смотрите соответствующую команду в основном разделе.
.SH ОПИСАНИЕ
В данном меню собраны практически все команды, которые можно делать из консоли. Суть их действия - та же.
