.TH mpkg-getrepositorylist 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-getrepositorylist
.SH СИНТАКСИС
.B mpkg-getrepositorylist
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I URL
.SH ОПИСАНИЕ
Загрузка списка репозиториев с сервера. По умолчанию, список берется из http://mopspackages.ru/repository_list Все существующие в текущем профиле репозитории помечаются 
.B отключенными,
но не удаляются. 
.B URL
опциональный параметр, его можно указать в случае, если список нужно получить из альтернативного источника.
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
