.TH mpkg-show 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-show
.SH СИНТАКСИС
.B mpkg-show
[
.B -g --dialog
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ПАКЕТА
.SH ОПИСАНИЕ
Вывод информации о пакете из базы данных.
.TP
Кроме того, можно явно указать версию и билд, разделяя знаком =, например: 
.TP
.B mpkg-show mc=4.3.6
.TP
.B mpkg-show mc=4.3.6=1
.SH КЛЮЧИ
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ПРИМЕР
.TP 
Показ информации о пакете amarok
.TP
.B mpkg-show amarok
.SH НЮАНСЫ
.TP
.B Порядок выбора пакета
Приоритет выбора пакета для отображения следующий: Если пакет установлен, то отображается информация об установленной версии. Если нет - то отображается информация о последней доступной версии. Указание версии (и опционально - билда) сужает область поиска. 
