#!/bin/sh
# WARNING: it is an update script for OLD-STYLE build system!
# TODO: remake it for new one
ARCH=`uname -m`

if [ "$ARCH" = "x86_64" ] ; then
	LIBDIRSUFFIX="64"
else
	LIBDIRSUFFIX=""
fi

cp -fv ../../nwidgets/build/libnwidgets.so initrd.new/usr/local/lib$LIBDIRSUFFIX/
cp -fv ../../mpkgsupport/build/libmpkgsupport.so initrd.new/usr/local/lib$LIBDIRSUFFIX/
cp -fv ../../lib/build/libmpkg.so initrd.new/usr/local/lib$LIBDIRSUFFIX/
cp -fv ../../console/build/mpkg initrd.new/usr/local/bin/
cp -fv ../build/setup initrd.new/usr/local/bin/
cp -fv ../../mparted/build/mparted initrd.new/usr/local/bin/
cp -fv ../../mparted/build/libmparted.so initrd.new/usr/local/lib$LIBDIRSUFFIX/
cp -fv ../../i18n/build/ru.gmo initrd.new/usr/local/share/locale/ru/LC_MESSAGES/mpkg.mo
cp -fv ../../i18n/build/uk.gmo initrd.new/usr/local/share/locale/uk/LC_MESSAGES/mpkg.mo
cp -fv ../../console/aliases/mpkg-* initrd.new/usr/local/bin/
cp -fv ../../console/build/mpkg-* initrd.new/usr/local/bin/

cp -fv ../../mpkg-parted/build/libmpkg-parted.so initrd.new/usr/local/lib$LIBDIRSUFFIX/
cp -fv ../../guiinstaller/guisetup/build/guisetup initrd.new/usr/local/bin/
cp -fv ../../guiinstaller/guisetup_exec/build/guisetup_exec initrd.new/usr/local/bin/
cp -fv ../../guiinstaller/langselect/build/guisetup_lang initrd.new/usr/local/bin/
cp -fv ../../guiinstaller/guisetup/*.qm initrd.new/usr/local/share/setup/l10n/
cp -fv ../../guiinstaller/guisetup_exec/*.qm initrd.new/usr/local/share/setup/l10n/
