#!/bin/sh
# This script builds all components and installs it into system (because of building requirements).
# Do not use this for package build
TARGETS="mpkgsupport nwidgets lib console i18n mpkg-parted manager2 mpkg-gui-installer guiinstaller textinstaller"
set -e
CWD=`pwd`
if [ `uname -m` = "i686" ] ; then
	MARCH="-march=i686"
fi
NUMJOBS=${NUMJOBS:--j4}
CXXFLAGS="-O0 $MARCH -pthread -g -DDEBUG"
export CXXFLAGS
CFLAGS=$CXXFLAGS
export CFLAGS

for i in $TARGETS ; do
	mkdir -p $CWD/$i/build
	cd $CWD/$i/build
	CXXFLAGS=$CXXFLAGS CFLAGS=$CFLAGS cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS:STRING="$CFLAGS" -DCMAKE_CXX_FLAGS:STRING="$CXXFLAGS" ..
	make $NUMJOBS
	sudo make install

done
cd $CWD
