#!/bin/sh
# This script builds all components and installs it into system (because of building requirements).
# Do not use this for package build
TARGETS="mpkgsupport nwidgets lib console i18n manager2 mpkg-gui-installer mpkg-parted libagiliasetup guiinstaller textinstaller"
set -e
CWD=`pwd`
for i in $TARGETS ; do
	rm -rf $CWD/$i/build
done
cd $CWD
