.TH mpkg-convert 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-convert
.SH СИНТАКСИС
.B mpkg-convert
[
.B -t --conf=ИМЯ_КОНФИГА
]
.SH ОПИСАНИЕ
Преобразование пакета из формата slackware в формат mpkg
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл. В данном контексте влияет только на тип пакета на выходе (tgz/txz).
