.TH mpkg-collectfileindex 0.16 "Ноябрь 2010"
.SH ИМЯ
mpkg-collectfileindex
.SH СИНТАКСИС
.B mpkg-collectfileindex
.I [ИМЯ_ВЫХОДНОГО_ФАЙЛА]
.SH ОПИСАНИЕ
Утилита для нужд репозитория, собирает filelist.tar.xz со всех прописанных в конфиге репозиториев и преобразовывает эти данные в SQL-файл для внутренней базы данных. Не предназначена для использования end-user'ами.
.TP
Если выходной файл не указан, создается filelist.sql в текущей директории. 
