.TH mpkg-convert_dir 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-convert_dir
.SH СИНТАКСИС
.B mpkg-convert_dir
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ДИРЕКТОРИИ
.SH ОПИСАНИЕ
Преобразование директории с пакетами формата slackware в формат mpkg.
.TP
.B ВНИМАНИЕ:
Данная функция давно не тестировалась, никем не используется, устарела и будет удалена в ближайшее время. Используйте 
.B mpkg-nativize.
Более того, никто толком не знает как она работает :) В целом, разница заключается в том что не производится проверка на то, сконвертирован ли уже пакет или нет.
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
