.TH mpkg-gendeps2 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-gendeps2
.SH СИНТАКСИС
.B mpkg-gendeps2
[
.B -t --conf=ИМЯ_КОНФИГА
]
[
.B -P --noaaa
]
[
.B -G --keep-deps
]
[
.B -E --exclusion-list=ИМЯ_ФАЙЛА
]
.I ИМЯ_ФАЙЛА
.br
.B mpkg-gendeps2
[
.B -t --conf=ИМЯ_КОНФИГА
]
[
.B -P --noaaa
]
[
.B -G --keep-deps
]
[
.B -E --exclusion-list=ИМЯ_ФАЙЛА
]
.I ИМЯ_ДИРЕКТОРИИ
.SH ОПИСАНИЕ
Генерация зависимостей для пакета.
.TP
Это - вторая реализация системы генерации зависимостей. В отличие от старой mpkg-gendeps, которая использовала для данного процесса сторонний скрипт requiredbuilder и парсила его вывод, данная реализация полностью основана на собственном коде, и имеет несколько ключевых преимуществ:
.br
.B "* Значительно быстрее"
.br
.B "* Работает при запуске через sudo"
.br
.B "* Поддерживает x86_64"
.br
.B "* Точнее и правильнее определяет зависимости"
.br
.B "* Не зависит от наличия сторонних утилит"
.SH НЕОБХОДИМЫЕ УСЛОВИЯ ДЛЯ ПРАВИЛЬНОГО РЕЗУЛЬТАТА
Чтобы зависимости сгенерировались правильно, необходимо чтобы 
.B все пакеты, которые нужны для работоспособности данного пакета, были установлены.
Иными словами, пакет должен быть полностью работоспособен в системе, на которой проводится генерация зависимостей. В противном случае генерация выполнена не будет, либо результат будет неполным, и как следствие - некорректным.
.br
.B Для мейнтейнеров:
помните, что все зависимости пакета должны быть в репозитории, либо добавляться вместе с ним.
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.TP
.B -P --noaaa
Пытаться избежать попадания aaa_elflibs в генерируемый список зависимостей.
.TP
.B -G --keep-deps
не заменять зависимости, уже имеющиеся в пакете, а дополнять их.
.TP
.B -E --exclusion-list=ИМЯ_ФАЙЛА
Использовать список исключений. Файлы, указанные в данном списке, обрабатываться не будут. 
.br
.B ВАЖНО:
В начале 
.B НЕ
должно быть слэша (/). Если хотите заблэклистить всю директорию - используйте звездочку на конце.
