.TH mpkg-gendeps 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-gendeps
.SH СИНТАКСИС
.B mpkg-gendeps
[
.B -t --conf=ИМЯ_КОНФИГА
]
.SH ОПИСАНИЕ
Генерация зависимостей для пакета.
.TP
.B ВНИМАНИЕ:
Данная функция устарела и обладает некоторыми существенными недостатками. Используйте mpkg gendeps2. В очень скором будущем данные команды станут синонимами.
.TP
Для работоспособности данной функции требуется requiredbuilder. Запускать нужно от root (не работает через sudo), иначе на выходе будет пустой список.
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
