#!/bin/bash


export REAL_HOME="$HOME"

# Checking if ISOBUILD exists
if [ ! -r "ISOBUILD" ] ; then
	echo "Sorry, no ISOBUILD file here, aborting"
	exit 1
fi

# Loading configs. Note that they will be loaded twice - once here, and next in fakeroot environment

# Loading global config
if [ -r "/etc/mklivecd.conf" ] ; then
	. /etc/mklivecd.conf
fi

# Loading local user config
if [ -r "${REAL_HOME}/.mklivecd.conf" ] ; then
	. ${REAL_HOME}/.mklivecd.conf
fi

# Checking and defining variables
export ISO_OUTPUT=${output_dir:-${REAL_HOME}/.mklivecd/iso}
export BUILD_ROOT=${output_dir:-${REAL_HOME}/.mklivecd/build}
export startdir=`pwd`


if [ "`id -u`" != "0" ] ; then
	FAKEROOT=fakeroot
fi

$FAKEROOT create-livecd.sh

