.TH mpkg-index 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-index
.SH СИНТАКСИС
.B mpkg-index
[
.B -v --verbose
]
[
.B -g --dialog
]
[
.B -C --enable-cache
]
[
.B -W --enable-spkg-index
]
.I [ПУТЬ_К_РЕПОЗИТОРИЮ]
.SH ОПИСАНИЕ
Создание или обновление индекса репозитория.
Если путь не указан, индекс создается в текущей директории
.SH КЛЮЧИ
.TP
.B -v --verbose
Подробный вывод. В некоторых местах вывод будет чуть более подробным. 
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -C --enable-cache
Включить кеширование при индексации. Данный ключ существенно ускоряет процесс обновления индекса. Обновляются данные только новых пакетов, а так же пакетов, у которых изменился размер файла. 
.TP
.B -W --enable-spkg-index
Включить индексирование 
.B spkg
(по умолчанию - отключено).
