.TH mpkg-purge 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-purge
.SH СИНТАКСИС
.B mpkg-purge
[
.B -v --verbose
]
[
.B -g --dialog
]
[
.B -z --no-dep
]
[
.B -k --force-essential
]
[
.B -y --noconfirm
]
[
.B -q --noreset
]
[
.B -F --fork
]
[
.B -Q --enqueue
]
[
.B --sysroot=<DIR>
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
purge
.I ИМЯ_ПАКЕТА
.SH ОПИСАНИЕ
Удаление установленных пакетов
.TP
Можно указывать любое количество пакетов одновременно:
.TP
.B mpkg purge amarok skype splashy wxcam
.TP
Можно использовать '*' для имени пакета. Следует иметь ввиду, что этот символ в первую очередь обрабатывается шеллом, поэтому, для имен пакетов запрос лучше окружать в кавычки, например вот так:
.TP
.B mpkg purge 'alsa-*'
.SH КЛЮЧИ
.TP
.B -v --verbose
Подробный вывод. В некоторых местах вывод будет чуть более подробным. 
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -d --force-dep
Игнорировать ошибки зависимостей. Если какие-то зависимости не могут быть удовлетворены — они будут просто опускаться. Тем не менее, 
.B mpkg
будет пытаться разобраться с ними насколько это возможно.
.TP
.B -z --no-dep
Полностью игнорировать существование зависимостей. Вообще отключить зависимости, будто их нет вовсе. В отличие от 
.B --force-dep
,
.B mpkg
не будет предпринимать вообще никаких попыток разобраться с зависимостями. Таким образом, пакеты, зависящие от удаляемого, не будут удалены.
.TP
.B -k --force-essential
Разрешить удаление системных пакетов. Разрешить удаление пакетов, занесенных в «красную книгу» — список системных пакетов, без которых ничего работать не будет. 
.TP
.B -y --noconfirm
Не спрашивать подтверждений. Отключение запросов на подтверждение действий.
.TP
.B -q --noreset
Не сбрасывать очередь при запуске. По умолчанию, очередь сбрасывается перед установкой. Вы можете использовать этот ключ чтобы выполнить действия из очереди заодно с удалением ненужных пакетов. 
.TP
.B -F --fork
Отсоединиться от терминала и работать в фоновом режиме. С этим ключом 
.B mpkg
перейдет в режим демона. Для каких-то особых случаев может быть полезно.
.TP
.B -Q --enqueue
Поставить действия в очередь, не исполнять. Удаление будет добавлено в очередь, но выполняться не будет. Его можно будет проделать потом командой 
.B mpkg commit
или с ключом 
.B --noreset.
.TP
.B --sysroot=<DIR>
Временно переопределить путь к корню системы. Переопределить корень системы. Удобно, если вы управляете системой в chroot. 
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ПРИМЕР
.TP 
Полное удаление пакета kde-l10n-uk
.TP
.B mpkg purge kde-l10n-uk
.SH НЮАНСЫ
.B mpkg purge
и
.B mpkg remove,
де-факто, одна и та же команда. Хотя 
.B remove,
в отличие от 
.B purge,
должен оставлять конфигурационные файлы - на деле они нигде специальным образом не прописаны, и данное различие становится неактуальным.
