.TH buildsrcpkg 0.16 "Декабрь 2010"
.SH ИМЯ
buildsrcpkg
.SH СИНТАКСИС
.B buildsrcpkg
[
.B -t --conf=ИМЯ_КОНФИГА
]
.SH ОПИСАНИЕ
Создание spkg из текущей директории.
Директория должна содержать install/data.xml и быть правильной структуры. Подробнее смотрите 
.B spkg.
В нормальной ситуации, вам никогда не должна понадобиться эта функция.
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл. В данном контексте влияет только на тип пакета на выходе (tgz/txz).
