.TH mpkg-whodepend 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-whodepend
.SH СИНТАКСИС
.B mpkg-whodepend
[
.B -g --dialog
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ПАКЕТА
.SH ОПИСАНИЕ
Показывает, кто зависит от указанного пакета. Рассматриваются 
.B только пакеты, установленные в системе.
Указанный пакет тоже должен быть установлен.
.SH КЛЮЧИ
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ПРИМЕР
.TP 
Показ информации о пакетах, зависящих от glibc-solibs
.TP
.B mpkg-whodepend glibc-solibs
