.TH mpkg-reinstall 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-reinstall
.SH СИНТАКСИС
.B mpkg-reinstall
[
.B -v --verbose
]
[
.B -g --dialog
]
[
.B -f --force-conflicts
]
[
.B -m --no-md5
]
[
.B -D --download-only
]
[
.B -y --noconfirm
]
[
.B -q --noreset
]
[
.B -c --no_resume
]
[
.B -F --fork
]
[
.B -Q --enqueue
]
[
.B --sysroot=<DIR>
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
[
.B --download-to=<DIR>
]
[
.B -L --linksonly
]
.I ИМЯ_ПАКЕТА
.SH ОПИСАНИЕ
Переустановка пакета.
.TP
Используется в случаях когда пакет поврежден.
.SH КЛЮЧИ
.TP
.B -v --verbose
Подробный вывод. В некоторых местах вывод будет чуть более подробным. 
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -f --force-conflicts
Не выполнять проверку конфликтов файлов. Отключает проверку конфликтов файлов. Делать это КРАЙНЕ НЕ РЕКОМЕНДУЕТСЯ, данный ключ существует с доисторических времен и нужен в основном для отладки.
.TP
.B -m --no-md5
Не проверять целостность пакетов при установке. Отключение проверки контрольных сумм пакетов, которая по умолчанию происходит перед началом самой процедуры установки пакетов. Несколько ускоряет установку, однако появляется риск возникновения ошибки где-то посередине процесса из-за битого пакета.
.TP
.B -D --download-only
Только скачать пакеты, не устанавливать. С данным ключом пакеты будут выкачаны в кеш, и на этом процесс будет прерван. 
.TP
.B -y --noconfirm
Не спрашивать подтверждений. Отключение запросов на подтверждение действий.
.TP
.B -q --noreset
Не сбрасывать очередь при запуске. По умолчанию, очередь сбрасывается перед установкой. Вы можете использовать этот ключ чтобы выполнить действия из очереди заодно с установкой новых пакетов. 
.TP
.B -c --no_resume
Отключить докачку. Вообще говоря, докачка по умолчанию отключена. Однако если вы включили её в конфиге, вы можете временно отключить её. 
.TP
.B -F --fork
Отсоединиться от терминала и работать в фоновом режиме. С этим ключом 
.B mpkg
перейдет в режим демона. Для каких-то особых случаев может быть полезно.
.TP
.B -Q --enqueue
Поставить действия в очередь, не исполнять. Установка будет добавлена в очередь, но выполняться не будет. Её можно будет проделать потом командой 
.B mpkg commit
или с ключом 
.B --noreset.
.TP
.B --sysroot=<DIR>
Временно переопределить путь к корню системы. Переопределить корень системы. Удобно, если вы ставите пакеты для chroot. 
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.TP
.B --download-to=<DIR>
Скачать пакеты в указанную директорию. Можно использовать с ключом 
.B --download-only
, если хочется чтобы пакеты были выкачаны не в кеш а в указанную директорию. 
.TP
.B -L --linksonly
При выполнении 
.B install
или
.B upgradeall
, показывать ссылки для скачивания и выходить. Почти то же самое что и 
.B --download-only
, но вместо закачки пакетов будет выведен список ссылок на файлы, по которым потом можно будет скачать пакеты каким-нибудь сторонним менеджером закачек, например wget.
.SH ПРИМЕР
.TP 
Восстановление пакета kde-l10n-ru
.TP
.B mpkg reinstall kde-l10n-ru
.SH НЮАНСЫ
.TP
Перед переустановкой старый пакет не удаляется, а просто перезаписывается поверх. Зависимости не учитываются.

