#!/bin/sh
MODULES="mpkgsupport nwidgets mpkg-core mpkg-console mpkg-manager2 mpkg-i18n mpkg-parted mklivecd libagiliasetup agilia-gui-installer agilia-text-installer"

set -e
for i in $MODULES ; do
	( cd $i && mkpkg -si )
done
set +e

