.TH mpkg-check 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-check
.SH СИНТАКСИС
.B mpkg-check
[
.B --sysroot=<DIR>
]
[
.B -r --repair
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ПАКЕТА
.SH ОПИСАНИЕ
Проверка пакета или пакетов на целостность (в данный момент под целостностью понимается наличие всех файлов, которые были в пакете изначально. В планах - расширение функционала).
.SH КЛЮЧИ
.TP
.B --sysroot=<DIR>
Переопределить корень системы. Удобно, если вы ставите пакеты для chroot.
.TP
.B -r --repair
Восстанавливатьть поврежденные пакеты. С данным ключом все поврежденные пакеты будут переустановлены. 
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
