.TH mpkg-delete_rep 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-delete_rep
.SH СИНТАКСИС
.B mpkg-delete_rep
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I НОМЕР
.SH ОПИСАНИЕ
Выводит список репозиториев текущего профиля.
Номер должен соответствовать номеру репозитория. Чтобы узнать это, наберите
.B mpkg-list_rep.

Можно указывать несколько номеров подряд. 
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
