.TH mpkg-cleardeps 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-cleardeps
.SH СИНТАКСИС
.B mpkg-cleardeps
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ИМЯ_ФАЙЛА
.SH ОПИСАНИЕ
Очистка списка зависимостей пакета.
.br
Можно задавать несколько имен файлов. 
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл. В данном контексте влияет только на тип пакета на выходе (tgz/txz).
