.TH mpkg-create-deltas 0.16 "Ноябрь 2010"
.SH ИМЯ
mpkg-create-deltas
.SH СИНТАКСИС
.B mpkg-create-deltas
.SH ОПИСАНИЕ
Создание дельта-файлов в дереве репозитория.
.br
Работа команды осуществляется в текущей директории. Желательно иметь два конфигурационных файла: .deltapath и .oldpkgpath.
.TP
.B .deltapath
Файл должен содержать в себе путь к директории, в которую будут складироваться .dup-файлы дельта-обновлений.
.TP
.B .oldpkgpath
Файл должен содержать в себе пути к директориям, в которых лежат старые версии пакетов. Можно указывать несколько путей (по одному на каждой строчке). К этим путям всегда прибавляется текущая директория.
.TP
Если дельта уже существует, она не будет создаваться. Создаются дельты для обновления со всех предыдущих версий пакета до последней. Возможно, есть недокументированные особенности (есть предположение, что еще остались нюансы в виде того что пути должны быть относительными или абсолютными, и нюансы в виде необходимости завершающих слешей. Это всё нужно проверить и при необходимости исправить так, чтобы это не было важно).
.SH КЛЮЧИ
Отсутствуют
