.TH mpkg-nativize 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-nativize
.SH СИНТАКСИС
.B mpkg-nativize
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I [ИМЯ_ДИРЕКТОРИИ]
.SH ОПИСАНИЕ
Преобразование директории с пакетами формата slackware в формат mpkg. Идет поиск пакетов формата slackware в текущей директории и их преобразование в формат mpkg.
.TP
Если директория не указана, то используется текущая директория. 
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл. В данном контексте влияет только на тип пакета на выходе (tgz/txz).
