.TH mpkg-update 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-update
.SH СИНТАКСИС
.B mpkg-update
[
.B -g --dialog
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.SH ОПИСАНИЕ
Обновление информации из репозиториев. Данная команда необходима для того чтобы данные в локальной базе данных совпадали с данными в репозитории. С помощью неё 
.B mpkg
узнает о пакетах, которые находятся в репозиториях. Следует выполнять эту команду перед тем как устанавливать обновления или новые пакеты, так как состояние репозиториев меняется достаточно регулярно (иногда - по несколько раз в день).
.SH КЛЮЧИ
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ПРИМЕР
.TP 
Обновление информации из репозиториев.
.TP
.B mpkg-update
