all:
	#g++ -DDEBUG -g generate_index_new.cpp -I/usr/include/mysql -lmysqlclient -lmpkgsupport -o generate_index_new
	g++ -O2 generate_index_new.cpp -I/usr/include/mysql -lmysqlclient -lmpkgsupport -o generate_index_new

