.TH mpkg-exportinstalled 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-exportinstalled
.SH СИНТАКСИС
.B mpkg-exportinstalled
[
.B -V --enableverions
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I [ИМЯ_ВЫХОДНОГО_ФАЙЛА]
.SH ОПИСАНИЕ
Вывод списка всех известных пакетов
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.TP
.B -V --enableversions
Включить информацию о версиях в списке установленных пакетов
