.TH mpkg-removegroup 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-removegroup
.SH СИНТАКСИС
.B mpkg-removegroup
[
.B -v --verbose
]
[
.B -g --dialog
]
[
.B -z --no-dep
]
[
.B -k --force-essential
]
[
.B -y --noconfirm
]
[
.B -q --noreset
]
[
.B -F --fork
]
[
.B -Q --enqueue
]
[
.B --sysroot=<DIR>
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I ТЕГ
.SH ОПИСАНИЕ
Удаление всех установленных пакетов, имеющих указанный тег. 
.TP
Команда аналогична запуску 
.B mpkg-remove
с явным указанием всех пакетов, имеющих данный тег.
.SH КЛЮЧИ
.TP
.B -v --verbose
Подробный вывод. В некоторых местах вывод будет чуть более подробным. 
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -d --force-dep
Игнорировать ошибки зависимостей. Если какие-то зависимости не могут быть удовлетворены — они будут просто опускаться. Тем не менее, 
.B mpkg
будет пытаться разобраться с ними насколько это возможно.
.TP
.B -z --no-dep
Полностью игнорировать существование зависимостей. Вообще отключить зависимости, будто их нет вовсе. В отличие от 
.B --force-dep
,
.B mpkg
не будет предпринимать вообще никаких попыток разобраться с зависимостями. Таким образом, пакеты, зависящие от удаляемого, не будут удалены.
.TP
.B -k --force-essential
Разрешить удаление системных пакетов. Разрешить удаление пакетов, занесенных в «красную книгу» — список системных пакетов, без которых ничего работать не будет. 
.TP
.B -y --noconfirm
Не спрашивать подтверждений. Отключение запросов на подтверждение действий.
.TP
.B -q --noreset
Не сбрасывать очередь при запуске. По умолчанию, очередь сбрасывается перед установкой. Вы можете использовать этот ключ чтобы выполнить действия из очереди заодно с удалением ненужных пакетов. 
.TP
.B -F --fork
Отсоединиться от терминала и работать в фоновом режиме. С этим ключом 
.B mpkg
перейдет в режим демона. Для каких-то особых случаев может быть полезно.
.TP
.B -Q --enqueue
Поставить действия в очередь, не исполнять. Удаление будет добавлено в очередь, но выполняться не будет. Его можно будет проделать потом командой 
.B mpkg commit
или с ключом 
.B --noreset.
.TP
.B --sysroot=<DIR>
Временно переопределить путь к корню системы. Переопределить корень системы. Удобно, если вы управляете системой в chroot. 
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ПРИМЕР
.TP 
Полное удаление среды рабочего окружения KDE4
.TP
.B mpkg-removegroup kde4
