.TH mpkg-setprofile 0.16 "Ноябрь 2010"
.SH ИМЯ
mpkg-setprofile
.SH СИНТАКСИС
.B mpkg-setprofile
.I ИМЯ_ПРОФИЛЯ
.SH ОПИСАНИЕ
Загрузка профиля репозиториев, сохраненного ранее командой 
.B mpkg-saveprofile.
.br
Имя не должно содержать спецсимволов.
.br
Не забывайте, что после изменения списка репозиториев, вам необходимо сделать 
.B mpkg-update
для обновления информации из нового списка.
.SH ОПЦИИ
Отсутствуют
