#!/bin/bash
PKGNAME=$1
DIRNAME="."
if [ "$2"="-c" ] ; then
	DIRNAME="$PKGNAME"
fi

mkdir -p "$DIRNAME"
( cd "$DIRNAME" 
	wget http://api.agilialinux.ru/bt/$PKGNAME
	tar xf $PKGNAME-*.build_tree.tar.xz
	if [ "$3"="-e" ] ; then
		vim ABUILD
	fi
)
