.TH mpkg-search 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-search
.SH СИНТАКСИС
.B mpkg-search
[
.B -g --dialog
]
[
.B -i --installed
]
[
.B -a --available
]
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I СТРОКА_ПОИСКА
.SH ОПИСАНИЕ
Поиск пакетов по имени
.SH КЛЮЧИ
.TP
.B -g --dialog
Использовать диалоговый интерфейс. Режим вывода переключается в ncurses — как при установке системы.
.TP
.B -i --installed
Показывать только установленные пакеты.
.TP
.B -a --available
Показывать только доступные (доступный пакет — пакет, имеющийся в каком-либо из известных 
.B mpkg
репозиториев) пакеты.
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
.SH ОБОЗНАЧЕНИЯ СТАТУСА
У многих возникает вопрос, что же такое это 
.B [ AIC_ ].
Этот блок отображает статус пакета, каждая буква означает следующее:
.TP
.B A
Available (пакет доступен)
.TP
.B I
Installed (пакет установлен)
.TP
.B C
Config Exists (у пакета есть конфигурационные файлы). На самом деле этот флаг стоит у каждого пакета и, по сути, ничего не значит.
.TP
Последняя секция, которая обычно пустая (обозначена _), отведена для действий в очереди. Если пакет запланирован к удалению, установке или восстановлению, там будет соответствующая буква: 
.TP
.B i
install (установить пакет)
.TP
.B r
remove (удалить пакет)
.TP
.B p
purge (удалить пакет вместе с конфигурационными файлами)
.TP
.B u
update (обновить пакет)
.TP
.B R
repair (восстановить пакет)
.SH НЮАНСЫ
.TP 
Поиск не учитывает регистр символов. Поиск ведется по вхождению строки в имя пакета.
