.TH mpkg-validate 0.16 "Ноябрь 2010"
.SH ИМЯ
mpkg-validate
.SH СИНТАКСИС
.B mpkg-validate
.I ИМЯ_ФАЙЛА
.I [MOVE_FATALS_TO] [MOVE_BLOCKING_TO]
.SH ОПИСАНИЕ
Проверка пакета на соответствие правилам сборки пакетов.
.TP
.B MOVE_FATALS_TO
Директория, в которую следует перемещать все пакеты с фатальными ошибками (фатальными считаются неисправимые ошибки - например, пакет битый и не распаковывается). По умолчанию они никуда не перемещаются.
.TP
.B MOVE_BLOCKING_TO
Аналогично предыдущему, только для blocking-ошибок (blocking-ошибки - те ошибки, с которыми пакет нельзя класть в репозиторий, однако это может быть исправлено. Как правило, это отсутствие каких-нибудь зависимостей).
