.TH mpkg-disable_rep 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-disable_rep
.SH СИНТАКСИС
.B mpkg-disable_rep
[
.B -t --conf=ИМЯ_КОНФИГА
]
.I НОМЕР
.SH ОПИСАНИЕ
Временное отключение репозитория из текущего профиля.
Номер должен соответствовать номеру репозитория. Чтобы узнать это, наберите
.B mpkg-list_rep.

Можно указывать несколько номеров подряд. 
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл.
