.TH mpkg-checklist 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-checklist
.SH СИНТАКСИС
.B mpkg-checklist
.I [ИМЯ_ДИРЕКТОРИИ]
.SH ОПИСАНИЕ
Проверка целостности пакетов в репозитории. Для проверки необходимо наличие индекса репозитория, который содержит его корректное состояние. Данную функцию применяют тогда, когда необходимо проверить целостность и наличие на месте всех файлов в дереве.
.br
Если директория не указана - проверяется текущая. 
.SH КЛЮЧИ
Отсутствуют.
