.TH mpkg-export 0.16 "Декабрь 2010"
.SH ИМЯ
mpkg-export
.SH СИНТАКСИС
.B mpkg-export
[
.B -t --conf=ИМЯ_КОНФИГА
]
.SH ОПИСАНИЕ
Экспорт базы в формат, совместимый с pkgtools.
.TP
Если директория не указана, то по умолчанию экспорт идет в /var/log/packages/(Стандартной расположение базы для pkgtools). Следует отметить, что база в /var/log/packages синхронизируется автоматически, и ручная синхронизация не требуется. 
.SH КЛЮЧИ
.TP
.B -t --conf=ИМЯ_КОНФИГА
Использовать альтернативный конфигурационный файл. В данном контексте влияет только на тип пакета на выходе (tgz/txz).
